### ISSUE TITLE
Random crash on 1.20.4 while tried to enter End

### ISSUE THREAD

**Issue by sternschnaube** [AMereBagatelle/fabricskyboxes#103]
java.lang.NullPointerException: Cannot read field "field_1352" because "this.biomeColorVector" is null
	at net.minecraft.class_638.calcSkyColor(class_638.java:1236)
	at net.minecraft.class_638.handler$zgd000$badoptimizations$onGetColorHead(class_638.java:1221)
	at net.minecraft.class_638.method_23777(class_638.java)
	at io.github.amerebagatelle.fabricskyboxes.skyboxes.OverworldSkybox.render(OverworldSkybox.java:46)
	at io.github.amerebagatelle.fabricskyboxes.SkyboxManager.lambda$renderSkyboxes$2(SkyboxManager.java:132)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.amerebagatelle.fabricskyboxes.SkyboxManager.renderSkyboxes(SkyboxManager.java:130)
	at net.minecraft.class_761.handler$eng000$fabricskyboxes$renderCustomSkyboxes(class_761.java:9676)
	at net.minecraft.class_761.method_3257(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1014)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by FlashyReese** [comment]
This seems to be an issue caused by BadOptimizations and not us.

**Comment by sternschnaube** [comment]
Thanks.
